name = "is-news-cron"
main = "worker.js"
compatibility_date = "2026-02-10"

[triggers]
crons = ["*/5 * * * *"] # 5 mín fresti (mæli með, ekki 1 mín)

[[d1_databases]]
binding = "DB"
database_name = "is_news"
database_id = "b89f6b0f-c7e1-42f9-a8e2-a6ea1b56bb2a"
